# Generated by Django 5.2.4 on 2025-07-31 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ritual_type', models.CharField(choices=[('meditation', 'Meditation'), ('affirmation', 'Affirmation'), ('prompt', 'Journaling Prompt'), ('tarot', 'Tarot Reflection')], max_length=30)),
                ('content', models.TextField()),
                ('for_life_phase', models.CharField(choices=[('any', 'Any Phase'), ('transition', 'Life Transition'), ('motherhood', 'Motherhood'), ('career_stress', 'Career Stress'), ('healing', 'Healing Journey'), ('self_discovery', 'Self Discovery')], default='any', help_text='რომელი ფაზისთვის', max_length=50)),
                ('emotional_tone', models.CharField(choices=[('gentle', 'Gentle & Soothing'), ('empowering', 'Empowering & Strong'), ('grounding', 'Grounding & Centering'), ('uplifting', 'Uplifting & Joyful'), ('healing', 'Healing & Restorative')], default='gentle', max_length=30)),
                ('duration_minutes', models.IntegerField(default=5, help_text='Duration in minutes')),
                ('is_for_beginners', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('body_task', models.CharField(max_length=255)),
                ('work_task', models.CharField(max_length=255)),
                ('soul_task', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], help_text='ენერგიის დონე', null=True)),
                ('needs_today', models.TextField(blank=True, help_text='რა გჭირდება დღეს?', max_length=500)),
                ('gratitude_moment', models.TextField(blank=True, help_text='მადლიერების მომენტი', max_length=300)),
                ('emotional_support_needed', models.CharField(blank=True, choices=[('listening', 'Just Need to Be Heard'), ('guidance', 'Need Gentle Guidance'), ('encouragement', 'Need Encouragement'), ('grounding', 'Need Grounding'), ('celebration', 'Want to Celebrate')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
