# Generated by Django 5.2.4 on 2025-07-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ritual_type', models.CharField(choices=[('meditation', 'Meditation'), ('affirmation', 'Affirmation'), ('prompt', 'Journaling Prompt'), ('tarot', 'Tarot Reflection')], max_length=30)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
