# Generated by Django 5.2.4 on 2025-08-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='for_life_phase',
            field=models.CharField(
                choices=[
                    ('any', 'Any Phase'),
                    ('transition', 'Life Transition'),
                    ('motherhood', 'Motherhood'),
                    ('career_stress', 'Career Stress'),
                    ('healing', 'Healing Journey'),
                    ('self_discovery', 'Self Discovery'),
                ],
                default='any',
                help_text='რომელი ფაზისთვის',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='ritual',
            name='emotional_tone',
            field=models.CharField(
                choices=[
                    ('gentle', 'Gentle & Soothing'),
                    ('empowering', 'Empowering & Strong'),
                    ('grounding', 'Grounding & Centering'),
                    ('uplifting', 'Uplifting & Joyful'),
                    ('healing', 'Healing & Restorative'),
                ],
                default='gentle',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='ritual',
            name='duration_minutes',
            field=models.IntegerField(default=5, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='ritual',
            name='is_for_beginners',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ritual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='ritual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
