# Generated by Django 5.2.4 on 2025-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20250801_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='moodcheckin',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], help_text='Energy level', null=True),
        ),
        migrations.AlterField(
            model_name='moodcheckin',
            name='gratitude_moment',
            field=models.TextField(blank=True, help_text='Gratitude moment', max_length=300),
        ),
        migrations.AlterField(
            model_name='moodcheckin',
            name='needs_today',
            field=models.TextField(blank=True, help_text='What do you need today?', max_length=500),
        ),
        migrations.AlterField(
            model_name='ritual',
            name='for_life_phase',
            field=models.CharField(choices=[('any', 'Any Phase'), ('transition', 'Life Transition'), ('motherhood', 'Motherhood'), ('career_stress', 'Career Stress'), ('healing', 'Healing Journey'), ('self_discovery', 'Self Discovery')], default='any', help_text='For which life phase', max_length=50),
        ),
    ]
