# Generated by Django 5.2.6 on 2025-09-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ka', 'Georgian')], default='en', help_text='Language of the ritual content', max_length=10),
        ),
    ]
