# Generated by Django 5.2.4 on 2025-09-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_title_alter_moodcheckin_energy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodcheckin',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moodcheckin',
            name='emotional_support_needed',
        ),
        migrations.RemoveField(
            model_name='moodcheckin',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='moodcheckin',
            name='gratitude_moment',
        ),
        migrations.RemoveField(
            model_name='moodcheckin',
            name='needs_today',
        ),
    ]
