# Generated by Django 5.2.6 on 2025-09-25 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_ritual_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarotCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_major_arcana', models.BooleanField(default=False)),
                ('suit', models.CharField(choices=[('major', 'Major Arcana'), ('cups', 'Cups'), ('pentacles', 'Pentacles'), ('swords', 'Swords'), ('wands', 'Wands')], default='major', max_length=20)),
                ('upright_meanings', models.JSONField(default=list, help_text='Keywords for upright position')),
                ('reversed_meanings', models.JSONField(default=list, help_text='Keywords for reversed position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_major_arcana', 'suit', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_type', models.CharField(choices=[('tarot', 'Tarot Reading'), ('general', 'General Chat'), ('guidance', 'Life Guidance'), ('reflection', 'Self Reflection')], max_length=20)),
                ('user_message', models.TextField(help_text="User's message to AI")),
                ('ai_response', models.TextField(help_text="AI's response")),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context for the conversation')),
                ('is_favorite', models.BooleanField(default=False, help_text='User marked as favorite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TarotDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(related_name='decks', to='journal.tarotcard')),
            ],
        ),
        migrations.CreateModel(
            name='TarotPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('single_card', 'Single Card'), ('three_card', 'Three Card Spread'), ('celtic_cross', 'Celtic Cross'), ('daily', 'Daily Reading'), ('custom', 'Custom Prompt')], max_length=20)),
                ('question', models.TextField(blank=True, help_text="User's question or intention")),
                ('cards_drawn', models.JSONField(default=list, help_text='List of drawn cards with positions')),
                ('interpretation', models.TextField(blank=True, help_text='AI-generated interpretation')),
                ('advice', models.TextField(blank=True, help_text='Advice based on the reading')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
