# Generated by Django 5.2.4 on 2025-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_remove_moodcheckin_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodcheckin',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='emotional_support_needed',
            field=models.CharField(blank=True, choices=[('listening', 'Just Need to Be Heard'), ('guidance', 'Need Gentle Guidance'), ('encouragement', 'Need Encouragement'), ('grounding', 'Need Grounding'), ('celebration', 'Want to Celebrate')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], help_text='Energy level', null=True),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='gratitude_moment',
            field=models.TextField(blank=True, help_text='Gratitude moment', max_length=300),
        ),
        migrations.AddField(
            model_name='moodcheckin',
            name='needs_today',
            field=models.TextField(blank=True, help_text='What do you need today?', max_length=500),
        ),
    ]
