# Generated by Django 5.2.6 on 2025-09-19 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WisdomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Main wisdom message')),
                ('affirmation', models.CharField(blank=True, max_length=500)),
                ('for_mood_context', models.CharField(choices=[('any', 'Any Context'), ('transition', 'Life Transition'), ('motherhood', 'Motherhood'), ('career_focus', 'Career Focus'), ('healing', 'Healing'), ('growth', 'Personal Growth')], default='any', max_length=50)),
                ('for_support_style', models.CharField(choices=[('any', 'Any Style'), ('gentle', 'Gentle'), ('empowering', 'Empowering'), ('practical', 'Practical'), ('spiritual', 'Spiritual')], default='any', max_length=30)),
                ('for_energy_level', models.CharField(choices=[('any', 'Any Energy Level'), ('low', 'Low Energy (1-2)'), ('moderate', 'Moderate Energy (3)'), ('high', 'High Energy (4-5)')], default='any', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mood_context', models.CharField(blank=True, choices=[('transition', 'Life Transition'), ('motherhood', 'Motherhood Journey'), ('career_focus', 'Career Focus'), ('healing', 'Healing Phase'), ('growth', 'Personal Growth'), ('balance', 'Seeking Balance')], help_text='What phase of life are you in', max_length=50, null=True)),
                ('preferred_support_style', models.CharField(choices=[('gentle', 'Gentle & Nurturing'), ('empowering', 'Empowering & Strong'), ('practical', 'Practical & Grounded'), ('spiritual', 'Spiritual & Soulful')], default='gentle', help_text='Preferred support style', max_length=30)),
                ('life_roles', models.JSONField(blank=True, default=list, help_text='Life roles - mother, professional, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RitualUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Did this ritual help?', null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, choices=[(1, 'Not helpful at all'), (2, 'Somewhat helpful'), (3, 'Moderately helpful'), (4, 'Very helpful'), (5, 'Extremely helpful')], help_text='How effective was this ritual?', null=True)),
                ('mood_before', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='How were you feeling before the ritual?', max_length=20, null=True)),
                ('mood_after', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='How were you feeling after the ritual?', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional thoughts about this ritual')),
                ('ritual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ritual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('user', 'ritual', 'used_at')},
            },
        ),
        migrations.CreateModel(
            name='UserWisdomDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wisdom_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.wisdommessage')),
            ],
            options={
                'unique_together': {('user', 'wisdom_message', 'delivered_at')},
            },
        ),
    ]
