# Generated by Django 5.2.4 on 2025-07-31 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WisdomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Main wisdom message')),
                ('affirmation', models.CharField(blank=True, max_length=500)),
                ('for_mood_context', models.CharField(choices=[('any', 'Any Context'), ('transition', 'Life Transition'), ('motherhood', 'Motherhood'), ('career_focus', 'Career Focus'), ('healing', 'Healing'), ('growth', 'Personal Growth')], default='any', max_length=50)),
                ('for_support_style', models.CharField(choices=[('any', 'Any Style'), ('gentle', 'Gentle'), ('empowering', 'Empowering'), ('practical', 'Practical'), ('spiritual', 'Spiritual')], default='any', max_length=30)),
                ('for_energy_level', models.CharField(choices=[('any', 'Any Energy Level'), ('low', 'Low Energy (1-2)'), ('moderate', 'Moderate Energy (3)'), ('high', 'High Energy (4-5)')], default='any', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWisdomDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wisdom_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.wisdommessage')),
            ],
            options={
                'unique_together': {('user', 'wisdom_message', 'delivered_at')},
            },
        ),
    ]
