# Generated by Django 5.2.6 on 2025-09-22 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MindfulnessActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('short_description', models.CharField(blank=True, help_text='Brief description for cards', max_length=255)),
                ('icon', models.CharField(default='leaf', help_text='Icon name from the icon set', max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=5, help_text='Estimated duration in minutes')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='mindfulness/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mindfulness/images/')),
                ('category', models.CharField(choices=[('breathing', 'Breathing Exercises'), ('meditation', 'Meditation'), ('body_scan', 'Body Scan'), ('gratitude', 'Gratitude Practice'), ('visualization', 'Visualization'), ('movement', 'Gentle Movement')], default='meditation', help_text='Type of mindfulness activity', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Difficulty level of the activity', max_length=20)),
                ('title_ka', models.CharField(blank=True, help_text='Title in Georgian', max_length=200)),
                ('description_ka', models.TextField(blank=True, help_text='Description in Georgian')),
                ('short_description_ka', models.CharField(blank=True, help_text='Short description in Georgian', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MindfulnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Actual duration in minutes')),
                ('mood_before', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='How were you feeling before the session?', max_length=20, null=True)),
                ('mood_after', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='How are you feeling after the session?', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any reflections or notes about this session')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='wellness.mindfulnessactivity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindfulness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
