# Generated by Django 5.2.4 on 2025-07-31 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mood_context', models.CharField(blank=True, choices=[('transition', 'Life Transition'), ('motherhood', 'Motherhood Journey'), ('career_focus', 'Career Focus'), ('healing', 'Healing Phase'), ('growth', 'Personal Growth'), ('balance', 'Seeking Balance')], help_text='რა ფაზაშია ცხოვრებაში', max_length=50, null=True)),
                ('preferred_support_style', models.CharField(choices=[('gentle', 'Gentle & Nurturing'), ('empowering', 'Empowering & Strong'), ('practical', 'Practical & Grounded'), ('spiritual', 'Spiritual & Soulful')], default='gentle', help_text='მხარდაჭერის სტილი', max_length=30)),
                ('life_roles', models.JSONField(blank=True, default=list, help_text='მისი როლები - დედა, თანამშრომელი, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
