# Generated by Django 5.2.4 on 2025-08-01 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20250801_0919'),
        ('wellness', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='Did this ritual help?', null=True)),
                ('effectiveness_rating', models.IntegerField(blank=True, choices=[(1, 'Not helpful at all'), (2, 'Somewhat helpful'), (3, 'Moderately helpful'), (4, 'Very helpful'), (5, 'Extremely helpful')], help_text='How effective was this ritual?', null=True)),
                ('mood_before', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='How were you feeling before the ritual?', max_length=20, null=True)),
                ('mood_after', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('anxious', 'Anxious'), ('calm', 'Calm'), ('stressed', 'Stressed'), ('excited', 'Excited')], help_text='How were you feeling after the ritual?', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional thoughts about this ritual')),
                ('ritual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.ritual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
                'unique_together': {('user', 'ritual', 'used_at')},
            },
        ),
    ]
