# Generated by Django 5.2.4 on 2025-09-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_ritualusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_mood_context',
            field=models.CharField(blank=True, choices=[('transition', 'Life Transition'), ('motherhood', 'Motherhood Journey'), ('career_focus', 'Career Focus'), ('healing', 'Healing Phase'), ('growth', 'Personal Growth'), ('balance', 'Seeking Balance')], help_text='What phase of life are you in', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='life_roles',
            field=models.JSONField(blank=True, default=list, help_text='Life roles - mother, professional, etc.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_support_style',
            field=models.CharField(choices=[('gentle', 'Gentle & Nurturing'), ('empowering', 'Empowering & Strong'), ('practical', 'Practical & Grounded'), ('spiritual', 'Spiritual & Soulful')], default='gentle', help_text='Preferred support style', max_length=30),
        ),
    ]
