# Generated by Django 5.2.6 on 2025-09-29 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communityreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='communityreaction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_user_reaction_per_post'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('post', 'session_id'), name='unique_session_reaction_per_post'),
        ),
    ]
