# Generated by Django 5.2.6 on 2025-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildcareRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('routine_type', models.CharField(choices=[('feeding', 'Feeding'), ('sleep', 'Sleep'), ('play', 'Play'), ('hygiene', 'Hygiene'), ('medical', 'Medical'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherhoodJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('mood', models.CharField(blank=True, choices=[('overwhelmed', 'Overwhelmed'), ('joyful', 'Joyful'), ('exhausted', 'Exhausted'), ('grateful', 'Grateful'), ('frustrated', 'Frustrated'), ('proud', 'Proud'), ('anxious', 'Anxious'), ('peaceful', 'Peaceful')], max_length=20)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MotherhoodResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('podcast', 'Podcast'), ('book', 'Book'), ('app', 'App'), ('community', 'Community'), ('professional', 'Professional Help')], max_length=20)),
                ('category', models.CharField(choices=[('pregnancy', 'Pregnancy'), ('newborn', 'Newborn Care'), ('toddler', 'Toddler Development'), ('preschool', 'Preschool Age'), ('school_age', 'School Age'), ('teen', 'Teen Parenting'), ('self_care', 'Self-Care'), ('relationships', 'Relationships'), ('mental_health', 'Mental Health'), ('work_life', 'Work-Life Balance')], max_length=20)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RitualCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ritual Completion',
                'verbose_name_plural': 'Ritual Completions',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_type', models.CharField(choices=[('pregnancy', 'Pregnancy Support'), ('newborn', 'Newborn Support'), ('single_mom', 'Single Mom Support'), ('working_mom', 'Working Mom Support'), ('mental_health', 'Mental Health Support'), ('general', 'General Motherhood')], max_length=20)),
                ('description', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('max_members', models.IntegerField(default=50)),
                ('current_members', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
