# Generated by Django 5.2.6 on 2025-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mood_reminder', 'Mood Check-in Reminder'), ('task_reminder', 'Task Reminder'), ('journal_reminder', 'Journal Reminder'), ('community_post', 'New Community Post'), ('comment_reply', 'Comment Reply'), ('reaction_received', 'Reaction Received'), ('insight_ready', 'New Insight Available'), ('ritual_suggestion', 'Ritual Suggestion'), ('custom', 'Custom Notification')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_reminder_enabled', models.BooleanField(default=True)),
                ('mood_reminder_time', models.TimeField(default='09:00:00')),
                ('mood_reminder_days', models.JSONField(default=list)),
                ('task_reminder_enabled', models.BooleanField(default=True)),
                ('task_reminder_time', models.TimeField(default='08:00:00')),
                ('journal_reminder_enabled', models.BooleanField(default=True)),
                ('journal_reminder_time', models.TimeField(default='20:00:00')),
                ('community_notifications_enabled', models.BooleanField(default=True)),
                ('comment_notifications_enabled', models.BooleanField(default=True)),
                ('reaction_notifications_enabled', models.BooleanField(default=True)),
                ('insight_notifications_enabled', models.BooleanField(default=True)),
                ('weekly_insight_enabled', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=False)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('mood_reminder', 'Mood Check-in Reminder'), ('task_reminder', 'Task Reminder'), ('journal_reminder', 'Journal Reminder'), ('welcome', 'Welcome Message'), ('milestone', 'Milestone Achievement'), ('insight', 'Insight Notification'), ('ritual_suggestion', 'Ritual Suggestion')], max_length=30)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
